defaults:
  - _self_
  - model: small_qwen
  - sft: default

# Run configuration (parameters not in SFTConfig)
run:
  reward_min: -1  # default to no rejection sampling
  dataset_name: "ASSERT-KTH/Nano-SFT-SWE-Gym-gemini-2.5-flash"
  push_to_hub: false
  commit_hash: ""  # will be set automatically
  
  wandb_project: "CodesetModels"

hydra:
  job:
    chdir: false # Prevents Hydra from changing the working directory 